// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2zRvKQ8amGcEx1ePi9rEYj
// Component: P0VZZmyR4j
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_verse_2022.module.css"; // plasmic-import: 2zRvKQ8amGcEx1ePi9rEYj/projectcss
import sty from "./PlasmicNavIconMenu.module.css"; // plasmic-import: P0VZZmyR4j/css

import MenuIcon from "./icons/PlasmicIcon__Menu"; // plasmic-import: pRjLWBwGGHY/icon

export type PlasmicNavIconMenu__VariantMembers = {};

export type PlasmicNavIconMenu__VariantsArgs = {};
type VariantPropType = keyof PlasmicNavIconMenu__VariantsArgs;
export const PlasmicNavIconMenu__VariantProps = new Array<VariantPropType>();

export type PlasmicNavIconMenu__ArgsType = {};
type ArgPropType = keyof PlasmicNavIconMenu__ArgsType;
export const PlasmicNavIconMenu__ArgProps = new Array<ArgPropType>();

export type PlasmicNavIconMenu__OverridesType = {
  root?: p.Flex<"svg">;
};

export interface DefaultNavIconMenuProps {
  className?: string;
}

function PlasmicNavIconMenu__RenderFunc(props: {
  variants: PlasmicNavIconMenu__VariantsArgs;
  args: PlasmicNavIconMenu__ArgsType;
  overrides: PlasmicNavIconMenu__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <MenuIcon
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_tokens,
        sty.root
      )}
      role={"img"}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavIconMenu__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavIconMenu__VariantsArgs;
    args?: PlasmicNavIconMenu__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNavIconMenu__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicNavIconMenu__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNavIconMenu__ArgProps,
      internalVariantPropNames: PlasmicNavIconMenu__VariantProps
    });

    return PlasmicNavIconMenu__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavIconMenu";
  } else {
    func.displayName = `PlasmicNavIconMenu.${nodeName}`;
  }
  return func;
}

export const PlasmicNavIconMenu = Object.assign(
  // Top-level PlasmicNavIconMenu renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicNavIconMenu
    internalVariantProps: PlasmicNavIconMenu__VariantProps,
    internalArgProps: PlasmicNavIconMenu__ArgProps
  }
);

export default PlasmicNavIconMenu;
/* prettier-ignore-end */
