// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2zRvKQ8amGcEx1ePi9rEYj
// Component: YihdW5fuU6
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_verse_2022.module.css"; // plasmic-import: 2zRvKQ8amGcEx1ePi9rEYj/projectcss
import sty from "./PlasmicArrowLight.module.css"; // plasmic-import: YihdW5fuU6/css

import IconArrow2Icon from "./icons/PlasmicIcon__IconArrow2"; // plasmic-import: WfhCAK0v-AX/icon

export type PlasmicArrowLight__VariantMembers = {};

export type PlasmicArrowLight__VariantsArgs = {};
type VariantPropType = keyof PlasmicArrowLight__VariantsArgs;
export const PlasmicArrowLight__VariantProps = new Array<VariantPropType>();

export type PlasmicArrowLight__ArgsType = {};
type ArgPropType = keyof PlasmicArrowLight__ArgsType;
export const PlasmicArrowLight__ArgProps = new Array<ArgPropType>();

export type PlasmicArrowLight__OverridesType = {
  root?: p.Flex<"div">;
  img?: p.Flex<typeof p.PlasmicImg>;
  svg?: p.Flex<"svg">;
};

export interface DefaultArrowLightProps {
  className?: string;
}

function PlasmicArrowLight__RenderFunc(props: {
  variants: PlasmicArrowLight__VariantsArgs;
  args: PlasmicArrowLight__ArgsType;
  overrides: PlasmicArrowLight__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.PlasmicImg
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(sty.img)}
        displayHeight={"32px" as const}
        displayMaxHeight={"none" as const}
        displayMaxWidth={"100%" as const}
        displayMinHeight={"0" as const}
        displayMinWidth={"0" as const}
        displayWidth={"32px" as const}
        loading={"lazy" as const}
        src={{
          src: "/plasmic/verse_2022/images/ellipse3.svg",
          fullWidth: 32,
          fullHeight: 32,
          aspectRatio: 1
        }}
      />

      <IconArrow2Icon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(projectcss.all, sty.svg)}
        role={"img"}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img", "svg"],
  img: ["img"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof p.PlasmicImg;
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicArrowLight__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicArrowLight__VariantsArgs;
    args?: PlasmicArrowLight__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicArrowLight__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicArrowLight__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicArrowLight__ArgProps,
      internalVariantPropNames: PlasmicArrowLight__VariantProps
    });

    return PlasmicArrowLight__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicArrowLight";
  } else {
    func.displayName = `PlasmicArrowLight.${nodeName}`;
  }
  return func;
}

export const PlasmicArrowLight = Object.assign(
  // Top-level PlasmicArrowLight renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicArrowLight
    internalVariantProps: PlasmicArrowLight__VariantProps,
    internalArgProps: PlasmicArrowLight__ArgProps
  }
);

export default PlasmicArrowLight;
/* prettier-ignore-end */
