// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2zRvKQ8amGcEx1ePi9rEYj
// Component: giex4on_Lm
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_verse_2022.module.css"; // plasmic-import: 2zRvKQ8amGcEx1ePi9rEYj/projectcss
import sty from "./PlasmicSectionMarketingHeadline.module.css"; // plasmic-import: giex4on_Lm/css

export type PlasmicSectionMarketingHeadline__VariantMembers = {};

export type PlasmicSectionMarketingHeadline__VariantsArgs = {};
type VariantPropType = keyof PlasmicSectionMarketingHeadline__VariantsArgs;
export const PlasmicSectionMarketingHeadline__VariantProps =
  new Array<VariantPropType>();

export type PlasmicSectionMarketingHeadline__ArgsType = {};
type ArgPropType = keyof PlasmicSectionMarketingHeadline__ArgsType;
export const PlasmicSectionMarketingHeadline__ArgProps =
  new Array<ArgPropType>();

export type PlasmicSectionMarketingHeadline__OverridesType = {
  root?: p.Flex<"div">;
  text?: p.Flex<"div">;
};

export interface DefaultSectionMarketingHeadlineProps {
  className?: string;
}

function PlasmicSectionMarketingHeadline__RenderFunc(props: {
  variants: PlasmicSectionMarketingHeadline__VariantsArgs;
  args: PlasmicSectionMarketingHeadline__ArgsType;
  overrides: PlasmicSectionMarketingHeadline__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {"Download: The Ultimate Hospitality Tech Trend Guide 2022"}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSectionMarketingHeadline__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSectionMarketingHeadline__VariantsArgs;
    args?: PlasmicSectionMarketingHeadline__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSectionMarketingHeadline__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSectionMarketingHeadline__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSectionMarketingHeadline__ArgProps,
      internalVariantPropNames: PlasmicSectionMarketingHeadline__VariantProps
    });

    return PlasmicSectionMarketingHeadline__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSectionMarketingHeadline";
  } else {
    func.displayName = `PlasmicSectionMarketingHeadline.${nodeName}`;
  }
  return func;
}

export const PlasmicSectionMarketingHeadline = Object.assign(
  // Top-level PlasmicSectionMarketingHeadline renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicSectionMarketingHeadline
    internalVariantProps: PlasmicSectionMarketingHeadline__VariantProps,
    internalArgProps: PlasmicSectionMarketingHeadline__ArgProps
  }
);

export default PlasmicSectionMarketingHeadline;
/* prettier-ignore-end */
